### PR TITLE
Support for WASM with EMSCRIPTEN

### PR DESCRIPTION
**Pull request by maniatic0**
Hello! I'm playing with WASM through EMSCRIPTEN and decided to test the library to it 😄

Most of the changes are to the CMake file to get the right flags to the compiler.  

## Limitations

There are two big limitations though:

- Fenster is not supported as that would require a WebGL/WebGPU context to render
- OpenMP is not working. More info in the CMake file, but the short story is that the OpenMP library was recently ported and the lib is not included by default with the compiler (I might try later to compile it and link it, but probably won't commit it as that'll be a big change)

## Results

From running in my Chrome browser, I get the next numbers (MT numbers are wrong as OpenMP is not enabled):

```
tiny_bvh version 0.7.2 performance statistics (emcc 3.1 build)
----------------------------------------------------------------
BVH construction speed
warming caches...
- reference builder:  405.86ms for  152292 triangles - 249218 nodes, SAH=96.91
- fast AVX builder:   131.31ms for  152292 triangles - 248966 nodes, SAH=96.87
- HQ (SBVH) builder: 2948.63ms for  152292 triangles - 272018 nodes, SAH=94.88
BVH traversal speed
- CPU, coherent,   basic 2-way layout, ST:   5774.2ms for   7.68M rays =>   1.33MRay/s
- CPU, coherent,   alt 2-way layout,   ST:   5687.8ms for   7.68M rays =>   1.35MRay/s
- CPU, coherent,   soa 2-way layout,   ST:   6355.1ms for   7.68M rays =>   1.21MRay/s
- CPU, coherent,   basic 2-way layout, MT:   5564.1ms for   7.68M rays =>   1.38MRay/s
- CPU, coherent,   2-way, packets,     MT:   1318.4ms for   7.68M rays =>   5.83MRay/s
- CPU, coherent,   2-way, packets/SSE, MT:   1082.2ms for   7.68M rays =>   7.10MRay/s
Optimizing BVH... done (9.10s). New SAH=87.76
- CPU, coherent,   2-way optimized,    ST:   6000.2ms for   7.68M rays =>   1.28MRay/s
- CPU, incoherent, basic 2-way layout, MT:  11005.1ms for   7.68M rays =>   0.70MRay/s
```

image

## How to compile and run

0. Download the EMSCRIPTEN compiler [here](https://emscripten.org/docs/getting_started/downloads.html)
1. Start a terminal with the emsdk environment (For Windows ```emsdk\emsdk.bat activate latest```)
2. Configure CMake, e. g.: ```emcmake cmake -S . -B ./build/web -G "Ninja Multi-Config" -Demcc_threads=ON -Demcc_proxy_main=ON```
3. Build with: ``` cmake --build .\build\web\ --config Release```
4. Use a HTTP server for testing. E. g. with [this](https://github.com/maniatic0/emcc-test-server): ```python custom-http.py -d .\build\web\Release\```
5. Go to ```localhost:8000``` and click a HTML page to test 😄

### CODE REVIEW

**Comment by jbikker** [comment]
Looks good to me! I didn't do the CMake support myself so that's a bit harder to assess; I trust the CMake guy will jump in if anything needs refinement there.

**Comment by maniatic0** [comment]
Okok, thanks! 😄

**Comment by maniatic0** [comment]
Well, it took me more than expected to get OpenMP working, but here is the data

```
tiny_bvh version 0.8.0 performance statistics (emcc 3.1 build)
----------------------------------------------------------------
BVH construction speed
warming caches...
- reference builder:  431.77ms for  152292 triangles - 249218 nodes, SAH=96.91
- fast AVX builder:   135.89ms for  152292 triangles - 248966 nodes, SAH=96.87
- HQ (SBVH) builder: 3089.17ms for  152292 triangles - 272018 nodes, SAH=94.88
BVH traversal speed
- CPU, coherent,   basic 2-way layout, ST:   6040.9ms for   7.68M rays =>   1.27MRay/s
- CPU, coherent,   alt 2-way layout,   ST:   5923.9ms for   7.68M rays =>   1.30MRay/s
- CPU, coherent,   soa 2-way layout,   ST:   6638.6ms for   7.68M rays =>   1.16MRay/s
- CPU, coherent,   basic 2-way layout, MT:   1210.9ms for   7.68M rays =>   6.34MRay/s
- CPU, coherent,   2-way, packets,     MT:    216.0ms for   7.68M rays =>  35.56MRay/s
- CPU, coherent,   2-way, packets/SSE, MT:    163.0ms for   7.68M rays =>  47.13MRay/s
Optimizing BVH... done (9.90s). New: 272017 nodes, SAH=87.76
- CPU, coherent,   2-way optimized,    ST:   6287.2ms for   7.68M rays =>   1.22MRay/s
- CPU, incoherent, basic 2-way layout, MT:   1402.6ms for   7.68M rays =>   5.48MRay/s
```

So 84% time reduction for the best MT case 😄 1082.2ms -> 163.0ms

image

**Comment by jbikker** [comment]
Very nice! Will you make a new pull request?

**Comment by maniatic0** [comment]
I don't think so. I would need to change the cmake to pull the llvm project (quite massive), which would defeat the tiny part hehe. 

I made a script that compiles it for me at https://github.com/maniatic0/wasm-win-openmp-fix. Also, I use this envar to make it link against the test targets ```set CXXFLAGS=-I<OpenMP_Build>\build\include <OpenMP_Build>\build\lib\libomp.a -fopenmp=libomp```

**Comment by maniatic0** [comment]
Mmm, maybe I could add precompiled versions if you think it's alright

**Comment by jbikker** [comment]
Hm I can also link to your repo for those interested; precompiled LLVM
binaries is perhaps still a bit too much.

- Jacco.

**Pull request merged**
