### PR TITLE
add basic github CI using CMake to build

### LINKED ISSUE #6: The need for CI
I think it's going to be almost impossible to maintain this and not break it for 'alternative' platforms/compilers, without some sort of CI.

I have some limited experience setting up github workflows, and would be willing to make an attempt, if such a PR would be acceptable (after the usual review of course).

### PR DESCRIPTION
**Pull request by jeffamstutz**
Closes #6.

### CODE REVIEW

**Comment by jeffamstutz** [comment]
Results are on my fork, which will run on your repo after merging: https://github.com/jeffamstutz/tinybvh/actions/runs/11622244740

**Comment by jbikker** [comment]
Thank you! As a pure Visual Studio developer I am not familiar with this stuff so I will just gratefully add it. ;)

**Comment by eloj** [comment]
As written, you're trying to evaluate the concatenated path, which doesn't seem right. It'll become empty.

This seems to work for me, but I hacked up a test on my linux system so YMMV:

```cmake
target_include_directories(tiny_bvh_speedtest PRIVATE ${CMAKE_CURRENT_LIST_DIR}/external/OpenCL/inc)
```

**Comment by jbikker** [comment]
Awesome, thanks! I was very stuck here. :)

**Comment by eloj** [comment]
Looks like it's currently only added on the "if (NOT MSVC)" branch of the cmake configuration, probably not what you want(?)

**Comment by jbikker** [comment]
Oops, no, definitely not. That explains issues I'm having with msvc now. ;)

**Comment by jbikker** [comment]
That was the final issue. I can now get back to actually finishing tiny_ocl, and with that, add gpu ray tracing to speedtest. Thanks for your help!

**Pull request merged**
