### PR TITLE
Test the AVX builder too.

### PR DESCRIPTION
**Pull request by eloj**
This greatly increases the chance of catching breakage.

### CODE REVIEW

**Comment by eloj** [comment]
CI fails becaue the Fragment alignment issue on linux is now caught.

```console
Test project /home/runner/work/tinybvh/tinybvh/build
    Start 1: tiny_bvh_test
1/1 Test #1: tiny_bvh_test ....................***Exception: SegFault  0.22 sec
```

**Comment by jbikker** [comment]
I don't think this is needed; the speedtest utility already builds both with and without AVX so this should be covered already.

**Comment by eloj** [comment]
That only covers build-issues, not runtime issues though. This is the only executable that is current run by CI, and you probably don't want to run speedtest there.

**Comment by jbikker** [comment]
Good point.

**Pull request merged**
