### PR TITLE
(WIP) Mac version of tiny_bvh_pt

### PR DESCRIPTION
**Pull request by drd**
Tested on my M3 Max, it seems to get 20-30fps. 

No open_mp, but libdispatch is just sitting there, so let's try it! The overhead is quite noticeable, so I increased tile size,  and tweaked window size to match. I don't see much of a difference between 32/64, but 16x16 tiles seem to be a bit slower. No rigorous benchmarking has been performed.

If you're interested in incorporating this, I can clean it up with some ifdefs etc.

edit:

Wanted to make sure and say thanks for all the years of writing and sharing you've done. It's helped me a lot in my understanding of graphics programming :)

### CODE REVIEW

**Comment by jbikker** [comment]
Hello, and thanks for your kind words!
I checked the openmp situation on Mac: 
https://mac.r-project.org/openmp/ 
It's complicated... While it could be made to work that way, that wouldn't exactly keep the 'runs out of the box' experience. On the other hand, bringing in an alternative threading solution in example code may spook the Windows/Linux people. It will also complicate further development, e.g. when ray batch processing or BVH construction in tiny_bvh.h starts using threading. 
Maybe we could add a tiny_bvh_pt_mac to deal with this?

**Comment by drd** [comment]
I'd be interested in learning a bit more about how you see things evolving here. Since it's sample code, I understand the desire to keep it relatively straightforward. Can you say more about how you expect threading to work in the library itself?

**Comment by jbikker** [comment]
Maybe the threading in the path tracer can be solved with some recent C++ features? Not 'sane C++' but at least still the same on all platforms..

**Comment by jbikker** [comment]
Looks like it is enabled now. I simply had to specify the dev branch. This checks compilation only though. Speedtest has basic unit tests (exits with 1 whenever ray batch results differ more than 0.1% from reference) but that is a time-consuming test and I am not sure Github will appreciate that. :) I could quite easily turn that into a much quicker test (at a lower resolution); perhaps I should do that. This is all quite new to me, all I know is BVHs. ;)

**Pull request closed without merging**
